import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SessionProvider from './Providers';

import './globals.scss';
import './customize.scss';
import './override.scss';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  content,
}: Readonly<{
  children: React.ReactNode;
  content: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <SessionProvider>
          {children}
          {content}
        </SessionProvider>
      </body>
    </html>
  );
}
